apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dsm
  labels:
    name: dsm
spec:
  terminationGracePeriodSeconds: 120 # the Kubernetes default is 30 seconds and it may be not enough
  containers:
    - name: dsm
      image: vdsm/virtual-dsm
      ports:
        - containerPort: 5000
          protocol: TCP
      resources:
        limits:
          devices.kubevirt.io/kvm: 1
      securityContext:
        privileged: true
      env:
        - name: RAM_SIZE
          value: 4G
        - name: CPU_CORES
          value: "2"
        - name: DISK_SIZE
          value: "30G"  # Kubernetes uses Gi, but DSM uses GB
        - name: DISK_FMT
          value: "qcow2"
      volumeMounts:
        - mountPath: /storage
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: dsm-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dsm
spec:
  type: NodePort
  selector:
    name: dsm
  ports:
    - name: tcp-5000
      port: 5000
      targetPort: 5000
      nodePort: 31150
